name: Validate PR on dev branch

on:
  pull_request:
    types: [opened, synchronize]
    branches: [dev]
    paths:
      - 'CRM/Project/force-app/**'

jobs:
    validate-deployment-on-dev-org:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]' }}

        steps:
              uses: actions/setup-node@v4
              with:
                node-version: '18.18.0' # Specify the exact Node.js version required

            - name: Verify Node.js version
              run: node -v

            - name: Verify NodeJS
              run: node --version

            - name: Checkout source code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install Salesforce CLI
              run: |
                  npm install --global @salesforce/cli
                  sf --version

            - name: Install sfdx git delta
              run: |
                  echo y | sf plugins install sfdx-git-delta
                  sf plugins

            - name: Install Java
              run: |
                  sudo apt-get update
                  sudo apt install -y default-jdk

            - name: Install SFDX scanner
              run: sf plugins install @salesforce/sfdx-scanner

            - name: Authenticate to Integration Org
              run: sf org login sfdx-url --sfdx-url-file ./CRM/Project/authFile.json --alias integration --set-default

            - name: Create delta packages for new, modified or deleted metadata
              run: |
                  mkdir changed-sources
                  sf sgd source delta --to "HEAD" --from "HEAD^" --output-dir changed-sources/ --generate-delta --source-dir CRM/Project/force-app/

            - name: Scan code
              run: |
                  cd changed-sources
                  sf scanner run --format sarif --target './**/*.cls' --category "Design,Best Practices,Performance" --outfile 'apexScanResults.sarif'
                  cd ..

            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: changed-sources/apexScanResults.sarif

            - name: Check-only deploy delta changes - run all tests
              working-directory: CRM/Project
              run: |
                  ls -al ../../changed-sources
                  ls -al ../../changed-sources/CRM
                  ls -al ../../changed-sources/CRM/Project
                  ls -al ../../changed-sources/CRM/Project/force-app
                  ls -al ../../changed-sources/destructiveChanges
                  sf project deploy start \
                      --source-dir "../../changed-sources/CRM/Project/force-app" \
                      --dry-run \
                      --test-level RunLocalTests \
                      --json

            - name: Deploy destructive changes (if any)
              working-directory: CRM/Project
              run: |
                  if [ -d "../../changed-sources/destructiveChanges" ]; then
                      sf deploy metadata \
                          --metadata-dir "../../destructiveChanges" \
                          --dry-run \
                          --ignore-warnings
                  fi
